connections:
  default:
    host: localhost
    port: 5672
    username: admin
    password: admin

services:
  printer:
    consumer:
      exchange: general-sentiment-topic-x
      exchange_type: topic
      routing_key: some.*.key
      queue: general-sentiment-topic-q
    publisher:
      exchange: general-sentiment-x
      routing_key: general-sentiment-q