connections:
  default:
    host: localhost
    port: 5672
    username: user
    password: bitnami

services:
  splitter:
    consumer:
      exchange: general-sentiment-x
      routing_key: general-sentiment-q
      queue: general-sentiment-q
    publisher:
      exchange: test-x
      routing_key: test_queue

publishers:
  default:
    exchange: log-x
    exchange_type: topic
    routing_key: splitter.test_queue
